"""Onboarding a new agent onto the platform.

The JD asks for someone who works with the GTM and CS AI Leads to "onboard new
agents onto the shared platform correctly". Correctly is the load-bearing word,
and a written checklist does not get you it: checklists are skipped under time
pressure, and the agent that skipped one is the agent nobody owns two quarters
later.

So onboarding is a command, and the contract is enforced rather than documented:

  * an owner is required - an agent with no name against it cannot be woken up
  * tools must exist and are granted explicitly - the agent can touch nothing else
  * a review date is stamped now, so the registry can tell you what has gone stale
  * the handler is generated wired-up, so the first run is traced like any other

Everything the new agent inherits - tracing, retries, idempotency, circuit
breaking, the dashboard, the trace explainer - it gets by being on the platform,
not by copying code from a sibling agent. That is the difference between a
platform and a folder of scripts.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from typing import Any

from .config import REPO_ROOT

AGENT_TEMPLATE = '''"""{description}

Generated by `python cli.py new-agent`. Everything this agent needs from the
platform - tracing, retries, idempotency, tool permissions, the dashboard, the
plain-English trace explainer - it already has. Write the decision, not the
plumbing.
"""

from __future__ import annotations

from typing import Any

from agentplatform.observability import SKIPPED


def handle(ctx) -> dict[str, Any]:
    """Called once per matching event. `ctx` carries the trace, tools and config.

    ctx.event      the normalised trigger
    ctx.tools      only the vendors granted in config/registry.yaml
    ctx.trace      step(), decision(), record()
    ctx.warehouse  the golden record and audit trail
    """
    # 1. Gather what you need. Each call is traced, retried and idempotent.
    with ctx.trace.step("fetch_context") as step:
        account = ctx.tools.salesforce.call(
            "get_account", {{"account_id": ctx.event.account_id}}
        )
        step.set(account_name=account.get("name"))

    # 2. Decide. Record WHY, with the values behind it, or the run is unexplainable.
    should_act = True
    reason = "replace this with the real condition"
    ctx.trace.decision(
        "{name}_gate",
        "act" if should_act else "hold",
        reason,
        account_id=ctx.event.account_id,
    )

    if not should_act:
        ctx.trace.record("agent_skipped", SKIPPED, reason=reason)
        return {{"acted": False, "summary": f"skipped: {{reason}}"}}

    # 3. Act. The idempotency key stops a redelivered webhook acting twice.
    with ctx.trace.step("notify_slack"):
        ctx.tools.slack.call(
            "post_message",
            {{
                "channel": "#{channel}",
                "text": (
                    f"*{title}* - {{account.get('name')}}\\n"
                    f"{{reason}}\\n"
                    f"_Trace: {{ctx.trace.trace_id}}_"
                ),
                "trace_id": ctx.trace.trace_id,
            }},
            idempotency_key=f"{{ctx.event.event_id}}:slack",
        )

    return {{"acted": True, "summary": f"{name} acted on {{account.get('name')}}"}}
'''

REGISTRY_TEMPLATE = """
  - name: {name}
    version: "0.1.0"
    description: {description}
    owner: {owner}
    owner_email: {owner_email}
    owner_slack: "{owner_slack}"
    team: {team}
    handler: agents.{name}.agent:handle
    subscribes_to: [{subscribes}]
    tools: [{tools}]
    writes_golden_record: false
    last_reviewed: "{today}"
    review_interval_days: 90
    enabled: true
"""


class ScaffoldError(RuntimeError):
    """Onboarding refused. The message says which rule was broken."""


def create_agent(
    name: str, owner: str, subscribes_to: list[str], tools: list[str],
    description: str, team: str = "gtm-ai", owner_email: str | None = None,
) -> dict[str, Any]:
    """Generate the module and register the agent. Refuses invalid input."""
    from .clients import TRANSPORTS

    if not re.fullmatch(r"[a-z][a-z0-9_]{2,39}", name):
        raise ScaffoldError(
            f"'{name}' is not a valid agent name: lowercase letters, digits and "
            f"underscores, starting with a letter, 3-40 characters."
        )

    agent_dir = REPO_ROOT / "agents" / name
    if agent_dir.exists():
        raise ScaffoldError(f"agents/{name}/ already exists. Pick another name.")

    unknown = [t for t in tools if t not in TRANSPORTS]
    if unknown:
        raise ScaffoldError(
            f"unknown tool(s): {unknown}. Available: {sorted(TRANSPORTS)}. "
            f"A tool must exist before an agent can be granted it."
        )

    bad = [e for e in subscribes_to if "." not in e]
    if bad:
        raise ScaffoldError(
            f"event types must be dotted, e.g. 'health_score.dropped'. Got: {bad}"
        )

    if not owner:
        raise ScaffoldError("an owner is required: an agent nobody owns is an outage waiting.")

    # Slack is the notification path for the generated stub, so grant it.
    if "slack" not in tools:
        tools = [*tools, "slack"]

    agent_dir.mkdir(parents=True)
    (agent_dir / "__init__.py").write_text("")
    (agent_dir / "agent.py").write_text(
        AGENT_TEMPLATE.format(
            name=name, description=description,
            channel=name.replace("_", "-"),
            title=name.replace("_", " ").title(),
        )
    )

    registry_path = REPO_ROOT / "config" / "registry.yaml"
    entry = REGISTRY_TEMPLATE.format(
        name=name, description=description, owner=owner,
        owner_email=owner_email or f"{owner}@supermetrics.com",
        owner_slack="@" + owner.split(".")[0],
        team=team,
        subscribes=", ".join(subscribes_to),
        tools=", ".join(tools),
        today=date.today().isoformat(),
    )
    registry_path.write_text(registry_path.read_text().rstrip() + "\n" + entry)

    return {
        "name": name,
        "module": str(agent_dir.relative_to(REPO_ROOT) / "agent.py"),
        "registry": str(registry_path.relative_to(REPO_ROOT)),
        "subscribes_to": subscribes_to,
        "tools": tools,
        "owner": owner,
    }
